### PR TITLE
Adds leftTurn, rightTurn

### PR DESCRIPTION
**Pull request by koushik3**

### CODE REVIEW

**Comment by SpandanKumarSahu** [comment]
@koushik3 : I couldn't understand the reason behind turning at Point (i,j). When we call, rightTurn function, we pass an angle and a radius of curvature as its parameters. The bot, obviously turns at the place it is currently in. Similarly for leftTurn.
So, i and j should be v.x and v.y. And there should a parameter in the function to indicate the angle by which the bot should turn.

**Comment by SpandanKumarSahu** [comment]
@koushik3 And also, I merged Theerdha's PR. She changed test.cpp file. So, in order to merge your request, you first git pull, and then git rebase to the HEAD of the master branch. You'll encounter some conflicts because test.cpp was changed by both Theerdha and you. You can comment out that Theerdha's test.cpp and then add your codes. And then commit the changes including the ones above.

**Comment by koushik3** [comment]
By "takes turn at (i,j)" ,I meant that the bot move towards (i,j) from its current location and takes a turn towards right/left with "radius of curvature of turn" = R . 
(i.e, point (i,j) will be the point of intersection of bot's initial line of motion and the one after taking the turn)
turn : 90 degrees turn

**Comment by SpandanKumarSahu** [comment]
@shivangag @amitpathak09 @amanchandra333 @koushik3 
I am not sure if this would be a practically efficient way to bring about turns in a bot's path. So, I am tagging embedded guys who can have a better say at this.

**Comment by amanchandra333** [comment]
@koushik3 why do you want to define a radius of curvature? Ultimately you have only two control inputs, the linear velocity and the angular velocity which will determine velocities of each wheels. If you want to go from point A to point B, linear velocity will simply depend on the distance whereas the angular velocity will depend on the slope. The radius of curvature will depend on the control parameters for linear and angular velocity.

**Comment by SpandanKumarSahu** [comment]
@koushik3 @amanchandra333 
So, basically, you'll have to compute the right and left RPM, right?
That's what this function actually does : hides away the calculations, and reduces it into simpler parameters, which are more intuitive, for actual path planning.
And for that sake, there is a function, to give separate RPM input to the left and right wheels. But in that case, you'll have to figure out, what the value of the RPM will be, based on what motion you wish to follow.

**Comment by koushik3** [comment]
@amanchandra333 
I'm unable to understand the phrase "the angular velocity will depend on the slope." ,can you please elaborate it and yeah, rather than defining the radius,we can work with linear and angular velocities only.
@SpandanKumarSahu 
What are the functions that you are talking about?   (I'm unable to relate them)
PS: can we all sit and discuss at some time?

**Comment by SpandanKumarSahu** [comment]
@koushik3 
I was saying that to Aman Chandra, that why we need to have leftTurn and rightTurn functions. We can work with angular and linear velocity only, but would it not be very cumbersome, to do the calculations every time? Like if I need to move forward, I will have to calculate the left RPM, the right RPM, while I could have simply called forward function. Similarly, for turning left and right. It's like providing some simple, predefined motions .And on a plus, we have that function, of controlling the RPM of the left and right wheels separately, which was written by Nilay.

Sure. Post any time convenient to you. :)

**Comment by amanchandra333** [comment]
@SpandanKumarSahu even if you make the functions, you do need to give the RPMs right? we can simply have a go to point (a,b) function.
@koushik3 your angular velocity will depend on the diff between present orientation an the direction in which you want to go. omega = PID(slope between present and goal points - present_theta)

**Comment by SpandanKumarSahu** [comment]
@amanchandra333 Yeah, right, we can make a function like goToPoint(a,b). But then the distance between (a,b) and current position should be reasonably small. Plus, in the long run, it should either know about the obstacles, or the parameters  (a,b) should be according to the obstacles.
I will write up this function, soon.

**Comment by amanchandra333** [comment]
@SpandanKumarSahu the path to the goal will be a straight line initially and will change dynamically when obstacles are encountered. when this is done and running, we will divide the path in waypoints to make the traversal more efficient.

**Comment by SpandanKumarSahu** [comment]
@amanchandra333 But in whatever way you may divide the path, ultimately, it boils down to move from current position to another position, either using a straight path or a curved path. That is what I am trying to say here.

We'll talk about this more in tomorrow's meeting.
P.S. : Pathak full team meeting kyun rakha? Sirf embedded walon ka meeting hai.
@koushik3 If you can join us for a couple of minutes, it would be great. We will discuss and clarify things. Else, whatever output of the discussion is, I will mail you.

**Pull request closed without merging**
