### PR TITLE
smoothens acceleration and deceleration using curvefitting

### PR DESCRIPTION
**Pull request by theerdha**

### CODE REVIEW

**Comment by theerdha** [comment]
@SpandanKumarSahu  comment

**Comment by SpandanKumarSahu** [comment]
@theerdha 
* It is a practice not to include user generated or binary files, in the commit. So we can remove the POSE.txt file.
* Indentation in Line 18 : test.cpp
* The rest of the code looks good to me.

In order to revise your commits, google "git ammend"

**Comment by theerdha** [comment]
@SpandanKumarSahu

**Comment by SpandanKumarSahu** [comment]
LGTM!
@pranitbauva1997 I am merging this, okay?

**Pull request merged**
